config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # get '/items', to: 'items#index'
  resources :items, except: %i[destroy] do
    resources :bookings, only: %i[new create]
    resources :favorites, only: %i[new create]
    resources :reviews, only: %i[new create show]
  end
  resources :bookings, only: %i[show index edit update]
  delete '/bookings/:id', to: 'bookings#destroy', as: :delete_booking
  resources :favorites, only: %i[destroy index]
  delete 'items/:id', to: 'items#destroy', as: :delete_item
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  has_many :favorites, dependent: :destroy
  has_many_attached :photos

  validates :category, inclusion: { in: ["Big Dog", "Medium Dog", "Small Dog", "Multiple Dogs", "Woodland",
    "Beachfront", "City", "Home-from-home"] }

  include PgSearch::Model

  pg_search_scope :search_by_location_and_date_and_guests, against: [:location], using: { tsearch: { prefix: true } }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :item, dependent: :destroy
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items, through: :bookings
  has_many :reviews
  has_many :bookings
  has_many :favorites, dependent: :destroy
  validates :username, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :location])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :location])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_item_bookings, only: %i[create]

  def new
    @item = Item.find(params[:item_id])
  end

  def create
    @booking = Booking.new(booking_strong_params)
    @booking.item = @item
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking), notice: 'New booking successfully placed!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @item = @booking.item
  end

  def edit
    @booking = Booking.find(params[:id])
    @item = @booking.item_id
  end

  def update
    @booking = Booking.find(params[:id])
    @item = @booking.item_id
    @booking.update(booking_strong_params)
    redirect_to bookings_path, notice: "Booking updated!"
  end

  def index
    @bookings = Booking.all
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path, status: :see_other, notice: "Booking has been cancelled"
  end

  private

  def set_item_bookings
    @item = Item.find(params[:item_id])
  end

  def booking_strong_params
    params.require(:booking).permit(:item_id, :date_booked_start, :date_booked_end)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_item_fav, only: %i[new create]

  def new
    @favorite = Favorite.new
  end

  def create
    @favorite = Favorite.new
    @favorite.item = @item
    @favorite.user = current_user
    if @favorite.save
      redirect_to root_path, notice: "Added to Favorites!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @favorites = Favorite.all
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    redirect_to favorites_path, status: :see_other, notice: "Removed from Favorites"
  end

  private

  def set_item_fav
    @item = Item.find(params[:item_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @items = Item.all

    # Filter items based on search parameters
    if params[:location].present?
      @items = @items.where("location ILIKE ?", "%#{params[:location]}%")
    end

    if params[:check_in].present?
      @items = @items.where("date_available_from <= ?", params[:check_in])
    end

    if params[:check_out].present?
      @items = @items.where("date_available_until >= ?", params[:check_out])
    end

    if params[:guests].present?
      @items = @items.where("max_guests >= ?", params[:guests])
    end
  end

  def show
    @booking = Booking.new
    @review = Review.new
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_strong_params)
    if @item.save
      redirect_to item_path(@item), notice: 'New item successfully listed!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @item.update(item_strong_params)
    redirect_to item_path(@item)
  end

  def destroy
    @item.destroy
    redirect_to items_path, status: :see_other, notice: "Item has been deleted!"
  end

  private

  def item_strong_params
    params.require(:item).permit(:name, :description, :price, :max_guests, :category, :location, :date_available_from, :date_available_until, photos: [])
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @items = Item.all
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def show
    @reviews = Review.all(params[:id])
    @item = @review.item
  end

  def new
    @item = Item.find(params[:item_id])
    @review = Review.new
  end

  def create
    @item = Item.find(params[:item_id])
    @review = Review.new(review_strong_params)
    @review.item = @item
    @review.user = current_user
    if @review.save
      redirect_to item_path(@item), notice: "Thank you. Your review was submitted successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_strong_params
    params.require(:review).permit(:review_text, :review_title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<%= simple_form_for(@booking) do |f| %>
  <%= f.input :date_booked_start %>
  <%= f.input :date_booked_end %>
  <%= f.submit %>
<% end %>

app/views/bookings/index.html.erb
<div class="container">
  <h1 class="mt-4">My bookings</h1>
  <ul class="list-group">
    <% @bookings.each do |booking| %>
      <li class="list-group-item">
        <div class="d-flex justify-content-between align-items-center">
          <div>
            <span class="font-weight-bold"><%= booking.item.name %></span>
            <br>
            <small class="text-muted">Booked from <%= booking.date_booked_start %> to <%= booking.date_booked_end %></small>
          </div>
          <div>
            <%= link_to edit_booking_path(booking), class: "btn btn-primary btn-sm mr-2" do %>
              <i class="fas fa-edit"></i> Edit
            <% end %>
            <%= link_to delete_booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to cancel this booking?" }, class: "btn btn-primary btn-sm mr-2", remote: true do %>
              <i class="fas fa-times"></i> Cancel
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/bookings/new.html.erb
<h1>here will be option to make new booking</h1>
<%# <%= simple_form_for [@item, @booking] do |f| %>
  <%# <%= f.input :date_booked_start, as: :date, placeholder: "Enter the date you would like the booking to start" %>
  <%# <%= f.input :date_booked_end, as: :date, placeholder: "Enter the date you would like the booking to end" %>
  <%# <%= f.submit %>
<%# <% end %>

<%= link_to "Back to #{@item.name}", item_path(@item) %>

app/views/bookings/show.html.erb
<h1>Your booking has been placed for <%= "#{@item.name} in #{@item.location}" %></h1>
<p>Starting: <%= @booking.date_booked_start %></p>
<p>Until: <%= @booking.date_booked_end %></p>
<p>Price per night: $<%= "#{@item.price}" %></p>
<%= link_to "Back", item_path(@item) %>

app/views/favorites/index.html.erb
<div class="container mt-4">
  <h1 class="text-center mb-4">Favorites</h1>

  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <ul class="list-group list-group-flush">
            <% @favorites.each do |favorite| %>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <%= link_to favorite.item.name, item_path(favorite.item_id), class: "text-decoration-none text-dark" %>
                <%= link_to favorite_path(favorite), class: "btn btn-link text-danger p-0",
                            data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove this item from your favorites list?" } do %>
                  <i class="fas fa-times"></i>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/favorites/new.html.erb
<h3>Add to favorites?</h3>
<%# <form action="/items/:item_id/favorites" method="post">
  <input type="submit">
</form> %>
<%= simple_form_for [@item, @favorite], url: item_favorites_path(@item), method: :post do |f| %>
  <%= f.submit %>
<% end %>
<%= link_to "Back", root_path %>

app/views/items/edit.html.erb
<div class="container">
  <h1>Edit Your Listing</h1>
   <%= simple_form_for(@item, html: { class: "row g-3" }) do |f| %>
    <div class="col-md-6">
      <%= f.input :name, label: "Item Name", input_html: { class: "form-control" } %>
    </div>
    <div class="col-md-6">
      <%= f.input :price, label: "Price", input_html: { class: "form-control" } %>
    </div>
    <div class="col-md-12">
      <%= f.input :description, label: "Description", input_html: { class: "form-control" } %>
    </div>
    <div class="col-md-12">
      <%= f.input :location, label: "Location", input_html: { class: "form-control" } %>
    </div>
    <div class="col-md-6">
      <%= f.input :max_guests, label: "Max. Guests", input_html: { class: "form-control" } %>
    </div>
    <div class="col-md-6">
      <%= f.input :category, collection: ["Big Dog", "Medium Dog", "Small Dog", "Multiple Dogs", "Woodland",
        "Beachfront", "City", "Home-from-home"], prompt: "Select a category" %>
    </div>
    <div class="col-md-6">
      <%= f.input :date_available_from, label: "Available Date", input_html: { class: "form-control" } %>
    </div>
    <div class="col-md-6">
      <%= f.input :date_available_until, label: "Available Until", input_html: { class: "form-control" } %>
    </div>

    <div>
      <% if @item.photos.attached? %>
        <% @item.photos.each do |ph| %>
          <%= f.hidden_field :photos, multiple: true, value: ph.signed_id %>
        <% end %>
      <% end %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Save Changes", class: "btn btn-primary" %>
        <%= link_to "Back to Item", item_path(@item), class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>

app/views/items/index.html.erb
<div class="container mt-5">

  <!-- Cards Section -->
  <% if @items.present? %>
    <% @items.in_groups_of(3, false) do |row_items| %>
      <div class="row">
        <% row_items.compact.each do |item| %>
          <div class="col-md-4">
            <div class="card mb-4">
              <% if item.photos.present? %>
                <div id="carousel<%= item.id %>" class="carousel slide">
                  <div class="carousel-inner">
                    <% item.photos.each_with_index do |photo, index| %>
                      <div class="carousel-item <%= 'active' if index == 0 %>">
                        <%= cl_image_tag photo.key, class: "d-block w-100 rounded-top" %>
                      </div>
                    <% end %>
                  </div>
                  <% if item.photos.count > 1 %>
                    <a class="carousel-control-prev" href="#carousel<%= item.id %>" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carousel<%= item.id %>" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                    </a>
                  <% end %>
                </div>
              <% end %>
              <button class="favorite-btn far fa-heart"></button>
              <div class="card-body">
                <h5 class="card-title"><%= link_to item.name, item_path(item) %></h5>
                <div class="card-text d-flex justify-content-between align-items-center">
                  <p class="m-0">$<%= item.price %>/night</p>
                  <div class="location-wrapper">
                    <span class="location-text"><%= item.location %></span>
                    <i class="location-icon fas fa-map-marker-alt"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="row">
      <div class="col-md-12">
        <p>No results.</p>
      </div>
    </div>
  <% end %>
</div>
<div class="line"></div>

app/views/items/new.html.erb
<div class="container mt-5">
  <h1>Add new item</h1>
  <%= simple_form_for(@item, html: { class: "row g-3" }) do |f| %>
    <div class="col-md-6">
      <%= f.input :name, label: "Item Name", input_html: { class: "form-control" } %>
    </div>
    <div class="col-md-6">
      <%= f.input :price, label: "Price", input_html: { class: "form-control" } %>
    </div>
    <div class="col-md-12">
      <%= f.input :description, label: "Description", input_html: { class: "form-control" } %>
    </div>
    <div class="col-md-12">
      <%= f.input :location, label: "Location", input_html: { class: "form-control" } %>
    </div>
    <div class="col-md-6">
      <%= f.input :max_guests, label: "Max. Guests", input_html: { class: "form-control" } %>
    </div>
    <div class="col-md-6">
      <%= f.input :category, collection: ["Big Dog", "Medium Dog", "Small Dog", "Multiple Dogs", "Woodland",
        "Beachfront", "City", "Home-from-home"], prompt: "Select a category" %>
    </div>
    <div class="col-md-6">
      <%= f.input :date_available_from, label: "Available Date", input_html: { class: "form-control" } %>
    </div>
    <div class="col-md-6">
      <%= f.input :date_available_until, label: "Available Until", input_html: { class: "form-control" } %>
    </div>
    <div class="col-md-12">
      <%= f.input :photos, as: :file, label: "Upload Photos", input_html: { multiple: true, class: "form-control" } %>
    </div>
    <div class="col-md-12">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
  <% end %>
  <%= link_to "Back to search results", root_path, class: "btn btn-secondary mt-3 me-2" %>
  <%= link_to "Back to home", root_path, class: "btn btn-secondary mt-3" %>
</div>

app/views/items/show.html.erb
<script>
  document.addEventListener("DOMContentLoaded", function() {
  var startDateInput = document.getElementById('date_booked_start');
  var endDateInput = document.getElementById('date_booked_end');
  var totalPriceElement = document.getElementById('total-price');

  function updateTotalPrice() {
    var startDate = new Date(startDateInput.value);
    var endDate = new Date(endDateInput.value);
    var diffTime = endDate - startDate;
    var diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24)); // Number of days
    var pricePerDay = <%= @item.price %>;
    var totalPrice = diffDays * pricePerDay;
    totalPriceElement.textContent = "$" + totalPrice;
  }

  startDateInput.addEventListener('change', updateTotalPrice);
  endDateInput.addEventListener('change', updateTotalPrice);
});
</script>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <!-- Carousel -->
      <div id="carousel<%= @item.id %>" class="carousel slide mb-3 showpagecarousel">
        <div class="carousel-inner">
          <% @item.photos.each_with_index do |photo, index| %>
            <div class="carousel-item <%= 'active' if index == 0 %>">
              <%= cl_image_tag photo.key, class: "d-block w-100 h-auto rounded" %>
            </div>
          <% end %>
        </div>
        <% if @item.photos.count > 1 %>
          <a class="carousel-control-prev" href="#carousel<%= @item.id %>" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carousel<%= @item.id %>" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row justify-content-between align-items-start">
    <!-- Inside your view file -->
<div class="col-md-8">
  <!-- Title and Description with Edit and Delete buttons -->
  <h2 class="show-title">
    <%= @item.name %>
    <div class="btn-group ml-2" style="color: inherit;">
      <%= link_to edit_item_path(@item) do %>
        <i class="fas fa-edit"></i>
      <% end %>
      <%= link_to delete_item_path(@item), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, style: "margin-left: 10px;" do %>
        <i class="fas fa-trash-alt"></i>
      <% end %>
    </div>
  </h2>
  <!-- Use a custom class for description -->
  <p class="text-muted description-text"><%= @item.description %></p>
</div>

    <div class="col-md-4">
      <!-- Booking Card -->
      <%= simple_form_for [@item, @booking], html: { class: "d-flex mx-auto" } do |f| %>
        <div class="card booking-card" style="margin-left: auto;">
          <div class="card-body">
            <h5 class="card-title">Create new booking</h5>
            <div class="form-group">
              <%= f.label :date_booked_start, "Check In" %>
              <%= f.date_field :date_booked_start, class: "form-control", id: "date_booked_start" %>
            </div>
            <div class="form-group">
              <%= f.label :date_booked_end, "Check Out" %>
              <%= f.date_field :date_booked_end, class: "form-control", id: "date_booked_end" %>
            </div>
            <div class="form-group">
              <%= f.label :total_price, "Total Price" %>
              <div id="total-price" class="form-control">$0</div>
            </div>
            <div class="text-center mt-3">
              <%= f.submit "Reserve", class: "btn btn-primary btn-sm px-4" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!-- Modal Overlay -->
<div id="modalOverlay" class="modal-overlay">
  <div class="modal-content">
    <span class="close">&times;</span>
    <div id="fullCarousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <% @item.photos.each_with_index do |photo, index| %>
          <div class="carousel-item <%= 'active' if index == 0 %>">
            <%= cl_image_tag photo.key, class: "d-block w-100 h-auto rounded" %>
          </div>
        <% end %>
      </div>
      <% if @item.photos.count > 1 %>
        <a class="carousel-control-prev" href="#fullCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#fullCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <!-- Other content -->

  <h3><strong>Reviews</strong></h3>
  <div class="row">
    <% @item.reviews.each do |review| %>
      <div class="col-md-6 mb-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= review.review_title %></h5>
            <p class="card-text" style="font-size: 0.9rem;"><%= review.review_text %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div data-controller="toggle-button">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <button class="btn btn-primary rounded-circle mx-auto my-3 display-block" data-action="click->toggle-button#toggleReview" style="width: 40px; height: 40px;">
          <i class="fas fa-plus"></i>
        </button>
      </div>
    </div>

    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card mb-3" data-toggle-button-target="newReviewCard" style="display: none;">
          <div class="card-body">
            <h4 class="card-title">New Review</h4>
            <%= simple_form_for [@item, @review], html: { id: "newReviewForm" } do |f| %>
              <div class="form-group">
                <%= f.text_field :review_title, class: "form-control", placeholder: "Your name" %>
              </div>
              <div class="form-group">
                <%= f.text_area :review_text, class: "form-control", placeholder: "Write your review here", rows: 4 %>
              </div>
              <div class="form-group text-center">
                <%= f.submit "Submit review", class: "btn btn-primary" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function(){

    // Modal functionality
    var modal = document.getElementById('modalOverlay');
    var carousel = document.getElementById('carousel<%= @item.id %>');
    var span = document.getElementsByClassName("close")[0];

    if (carousel) {
      carousel.onclick = function() {
        modal.style.display = "block";
      }
    }

    if (span) {
      span.onclick = function() {
        modal.style.display = "none";
      }
    }

    window.onclick = function(event) {
      if (event.target == modal) {
        modal.style.display = "none";
      }
    }
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dogbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>

  <footer class="footer mt-5">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <p>&copy; 2024 Dogbnb. All rights reserved.</p>
      </div>
    </div>
  </div>
</footer>

</html>

app/views/pages/home.html.erb
<div class="container mt-5">
  <div class="row mb-3">
    <div class="col-md-12">
      <p></p>
    </div>
  </div>

  <!-- Cards Section -->
  <% if @items.present? %>
    <% @items.in_groups_of(3, false) do |row_items| %>
      <div class="row">
        <% row_items.compact.each do |item| %>
          <div class="col-md-4">
            <div class="card mb-4">
              <div id="carousel<%= item.id %>" class="carousel slide">
                <div class="carousel-inner">
                  <% item.photos.each_with_index do |photo, index| %>
                    <div class="carousel-item <%= 'active' if index == 0 %>">
                      <%= cl_image_tag photo.key, class: "d-block w-100 rounded-top" %>
                    </div>
                  <% end %>
                </div>
                <% if item.photos.count > 1 %>
                  <a class="carousel-control-prev" href="#carousel<%= item.id %>" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carousel<%= item.id %>" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                <% end %>
              </div>
              <%# add this item to favorites list %>
              <%= link_to new_item_favorite_path(item) do %>
                <button class="favorite-btn far fa-heart"></button>
              <% end %>
              <div class="card-body">
                <h5 class="card-title"><%= link_to item.name, item_path(item) %></h5>
                <div class="card-text d-flex justify-content-between align-items-center">
                  <p class="m-0">$<%= item.price %>/night</p>
                  <div class="location-wrapper">
                    <span class="location-text"><%= item.location %></span>
                    <i class="location-icon fas fa-map-marker-alt"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="row">
      <div class="col-md-12">
        <p>No items to display.</p>
      </div>
    </div>
  <% end %>
</div>
<div class="line"></div>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= simple_form_for [@item, @review] do |f| %>
  <%= f.input :review_title %>
  <%= f.input :review_text %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>